USE codeup_test_db;
INSERT INTO albums (artist, album_name, release_date,sales,genre)
VALUES  ('Michael Jackson', 'Thriller', 1982, 51.2, 'Pop, post-disco, funk, rock'),
        ('Mariah Carey', 'Music Box', 1993, 17.8, 'Pop, R&B'),
        ('Various artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 15, 'Rock and roll'),
        ('Eminem', 'The Eminem Show', 2002, 19.1, 'Hip hop'),
        ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 18.1, 'Film score'),
        ('Britney Spears', '...Baby One More Time', 1999, 19.9, 'Pop'),
        ('Nirvana', 'Nevermind', 1991, 17.8, 'Grunge, alternative rock'),
        ('Eric Clapton', 'Unplugged', 1992, 17, 'Acoustic rock, acoustic blues'),
        ('Queen', 'Greatest Hits', 1981, 20.6, 'Rock'),
        ('Phil Collins', 'No Jacket Required', 1985, 17.7, 'Pop rock'),
        ('Eminem', 'The Marshall Mathers LP', 2000, 17.5, 'Hip hop'),
        ('Linkin Park', 'Hybrid Theory', 2000, 17.2, 'Nu metal, rap metal, alternative metal'),
        ('U2', 'The Joshua Tree', 1987, 16.7, 'Rock'),
        ('Whitney Houston', 'Whitney Houston', 1985, 17.6, 'Pop, R&B'),
        ('Prince and The Revolution', 'Purple Rain', 1984, 15.7, 'Pop rock, new wave, R&B'),
        ('Bon Jovi', 'Slippery When Wet', 1986, 15.3, 'Hard rock, glam metal'),
        ('Carole King', 'Tapestry', 1971, 15.1, 'Pop'),
        ('Madonna', 'True Blue', 1986, 14.5, 'Pop, dance'),
        ('Simon & Garfunkel', 'Bridge over Troubled Water', 1970, 12.5, 'Folk rock'),
        ('George Michael', 'Faith', 1987, 13.9, 'Pop, R&B, funk, soul'),
        ('Elton John', 'Greatest Hits', 1974, 19.1, 'Pop'),
        ('Backstreet Boys', 'Millennium', 1999, 18.4, 'Pop'),
        ('Adele', '25', 2015, 19, 'Soul, pop, R&B'),
        ('Spice Girls', 'Spice', 1996, 16.4, 'Pop'),
        ('Ace of Base', 'Happy Nation/The Sign', 1993, 14.4, 'Pop'),
        ('Michael Jackson', 'HIStory: Past, Present and Future, Book I', 1995, 15.2, 'R&B, pop and hip hop'),
        ('Celine Dion', 'All the Way... A Decade of Song', 1999, 14.4, 'Pop'),
        ('Madonna', 'Like a Virgin', 1984, 16.2, 'Pop, dance'),
        ('Bon Jovi', 'Cross Road', 1994, 11.6, 'Hard rock, glam metal'),
        ('Elvis Presley', 'Elvis'' Christmas Album', 1957, 20.8, 'Christmas, pop, gospel, rock and roll'),
        ('Boston', 'Boston', 1976, 18.1, 'Arena rock, hard rock'),
        ('Mariah Carey', 'Daydream', 1995, 15.2, 'Pop, R&B'),
        ('Green Day', 'Dookie', 1994, 14.6, 'Pop punk, punk rock, alternative rock'),
        ('Shania Twain', 'The Woman in Me', 1995, 14.5, 'Country, pop'),
        ('Britney Spears', 'Oops!... I Did It Again', 2000, 14.4, 'Pop'),
        ('Whitney Houston', 'Whitney', 1987, 14.4, 'Pop, R&B'),
        ('Def Leppard', 'Hysteria', 1987, 13.9, 'Hard rock, glam metal'),
        ('Lauryn Hill', 'The Miseducation of Lauryn Hill', 1998, 13.7, 'Neo Soul, R&B and Hip Hop'),
        ('Tracy Chapman', 'Tracy Chapman', 1988, 13.3, 'Folk rock'),
        ('Lionel Richie', 'Can''t Slow Down', 1983, 12.3, 'Pop, R&B, soul'),
        ('Michael Jackson', 'Off the Wall', 1979, 11.7, 'Disco, pop, funk and R&B'),
        ('Fugees', 'The Score', 1996, 11.6, 'Alternative hip hop'),
        ('Oasis', '(What''s the Story) Morning Glory?', 1995, 11.6, 'Britpop, rock'),
        ('Celine Dion', 'The Colour of My Love', 1993, 11.1, 'Pop'),
        ('Elton John', 'Goodbye Yellow Brick Road', 1973, 9.6, 'rock, pop rock, glam rock'),
        ('Pink Floyd', 'Wish You Were Here', 1975, 9.2, 'Progressive rock, art rock, experimental rock')

